name: Primeiro Workflow

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  minor-CD:
    # Sem a tag needs o job de CD seria executado de forma paralela.
    # Dessa forma, a execução do CD depende do CI ser executado com sucesso.
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/ml-communication

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Baixando repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          # ref: ${{ github.ref_name }}

      - name: Incrementa versão minor
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          VERSION=`git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}'`
          git tag -a $VERSION -m "new release"
          
      - name: Configurando Python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # - name: Instalando dependências de publicação do pacote
      #   run: pip install -U build==1.2.1 twine==5.1.1

      # - name: Cria o diretório da distribuição
      #   run: python3 -m build

      # - name: Publish distribution 📦 to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/

      - name: Update package tag
        run: git push origin $VERSION
        